language: python

python:
    - 2.6
    - 2.7

virtualenv:
    system_site_packages: true

install:
    - pip install -q coveralls --use-mirrors

script:
    - PYTHONPATH=. coverage run setup.py test

after_success:
    - coveralls
