language: python

branches:
    only:
        - test
python:
#    - 2.6
    - 2.7
env:
    - DJANGO=1.4.5
    - DJANGO=1.5.1
virtualenv:
    system_site_packages: true
before_install:
    - phantomjs --webdriver=8150 &
install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt --use-mirrors
    - pip install discover==0.4.0
    - pip install selenium==2.28.0 
services:
    - memcache
before_script:
    - "python headless_tests/test/start_ghostdriver.py"
    - "cp headless_tests/settings.py openmrs/conf/local_settings.py"
script:
    - "python -m unittest discover -s headless_tests/test --pattern=VerifyPatient*.py"
#    - coverage run --source='.' ./bin/manage.py test openmrs	
#    - ./bin/manage.py test openmrs
after_success:
    - coveralls
