language: python

branches:
    only:
        - test
python:
#    - 2.6
    - 2.7
env:
    - DJANGO=1.4.5
    - DJANGO=1.5.1
    global:
      - "ARTIFACTS_AWS_REGION=us-east-1"
      - "ARTIFACTS_S3_BUCKET=chop_cbmi_tiu_travisci"
      - secure: ".......long encrypted string............."
      - secure: ".......another long encrypted string....."
virtualenv:
    system_site_packages: true
before_install:
#   - phantomjs --webdriver=8150 &
install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt --use-mirrors
    - pip install discover==0.4.0
    - pip install selenium==2.28.0 
services:
    - memcache
before_script:
    - "python headless_tests/test/start_ghostdriver.py"
    - "sleep 8"
    - "cp headless_tests/settings.py openmrs/conf/local_settings.py"
    - "./bin/manage.py runserver 0.0.0.0:8004 &"
    - "sleep 10"
    - "rm -rf headless_tests/test/screen_shots/*"
    - "rm -rf headless_tests/test/log/*"
    - "gem install travis-artifacts"
script:
    - "python -m unittest discover -s headless_tests/test --pattern=VerifyPatientMRN*.py"
#    - "python -m unittest discover -s headless_tests/test --pattern=VerifyPatientMRN000243.py"
    - "ls headless_tests/test/screen_shots"
#    - coverage run --source='.' ./bin/manage.py test openmrs	
#    - ./bin/manage.py test openmrs
after_success:
    - coveralls
